#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 21, 2019 07:15:59 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gui_support
from classdbcon import controldata
def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    gui_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("425x294+481+110")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        self.objarray = []
        self.control=controldata()
        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.141, rely=0.034, height=31, width=294)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 15")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Show Stdent_Information''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.376, rely=0.238, height=21, width=20)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''ID:''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.447, rely=0.238,height=20, relwidth=0.386)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        
        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.353, rely=0.34, height=21, width=38)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Name''')

        self.Entry1_1 = tk.Entry(top)
        self.Entry1_1.place(relx=0.447, rely=0.34,height=20, relwidth=0.174)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="black")
        self.Entry1_1.configure(insertbackground="black")
        self.Entry1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1.configure(selectforeground="black")

        self.Entry1_3 = tk.Entry(top)
        self.Entry1_3.place(relx=0.624, rely=0.34,height=20, relwidth=0.198)
        self.Entry1_3.configure(background="white")
        self.Entry1_3.configure(disabledforeground="#a3a3a3")
        self.Entry1_3.configure(font="TkFixedFont")
        self.Entry1_3.configure(foreground="#000000")
        self.Entry1_3.configure(highlightbackground="#d9d9d9")
        self.Entry1_3.configure(highlightcolor="black")
        self.Entry1_3.configure(insertbackground="black")
        self.Entry1_3.configure(selectbackground="#c4c4c4")
        self.Entry1_3.configure(selectforeground="black")

        self.Label3_4 = tk.Label(top)
        self.Label3_4.place(relx=0.282, rely=0.442, height=21, width=68)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#d9d9d9")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(foreground="#000000")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Depament''')

        self.Entry1_4 = tk.Entry(top)
        self.Entry1_4.place(relx=0.447, rely=0.442,height=20, relwidth=0.174)
        self.Entry1_4.configure(background="white")
        self.Entry1_4.configure(disabledforeground="#a3a3a3")
        self.Entry1_4.configure(font="TkFixedFont")
        self.Entry1_4.configure(foreground="#000000")
        self.Entry1_4.configure(highlightbackground="#d9d9d9")
        self.Entry1_4.configure(highlightcolor="black")
        self.Entry1_4.configure(insertbackground="black")
        self.Entry1_4.configure(selectbackground="#c4c4c4")
        self.Entry1_4.configure(selectforeground="black")

        self.Entry1_5 = tk.Entry(top)
        self.Entry1_5.place(relx=0.635, rely=0.442,height=20, relwidth=0.198)
        self.Entry1_5.configure(background="white")
        self.Entry1_5.configure(disabledforeground="#a3a3a3")
        self.Entry1_5.configure(font="TkFixedFont")
        self.Entry1_5.configure(foreground="#000000")
        self.Entry1_5.configure(highlightbackground="#d9d9d9")
        self.Entry1_5.configure(highlightcolor="black")
        self.Entry1_5.configure(insertbackground="black")
        self.Entry1_5.configure(selectbackground="#c4c4c4")
        self.Entry1_5.configure(selectforeground="black")

        self.Label3_3 = tk.Label(top)
        self.Label3_3.place(relx=0.306, rely=0.544, height=21, width=68)
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#d9d9d9")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(foreground="#000000")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''Email''')

        self.Entry1_6 = tk.Entry(top)
        self.Entry1_6.place(relx=0.447, rely=0.544,height=20, relwidth=0.386)
        self.Entry1_6.configure(background="white")
        self.Entry1_6.configure(disabledforeground="#a3a3a3")
        self.Entry1_6.configure(font="TkFixedFont")
        self.Entry1_6.configure(foreground="#000000")
        self.Entry1_6.configure(highlightbackground="#d9d9d9")
        self.Entry1_6.configure(highlightcolor="black")
        self.Entry1_6.configure(insertbackground="black")
        self.Entry1_6.configure(selectbackground="#c4c4c4")
        self.Entry1_6.configure(selectforeground="black")

        self.Label3_1 = tk.Label(top)
        self.Label3_1.place(relx=0.306, rely=0.612, height=31, width=68)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(activeforeground="black")
        self.Label3_1.configure(background="#d9d9d9")
        self.Label3_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1.configure(foreground="#000000")
        self.Label3_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1.configure(highlightcolor="black")
        self.Label3_1.configure(text='''Date''')

        self.Entry1_7 = tk.Entry(top)
        self.Entry1_7.place(relx=0.447, rely=0.646,height=20, relwidth=0.386)
        self.Entry1_7.configure(background="white")
        self.Entry1_7.configure(disabledforeground="#a3a3a3")
        self.Entry1_7.configure(font="TkFixedFont")
        self.Entry1_7.configure(foreground="#000000")
        self.Entry1_7.configure(highlightbackground="#d9d9d9")
        self.Entry1_7.configure(highlightcolor="black")
        self.Entry1_7.configure(insertbackground="black")
        self.Entry1_7.configure(selectbackground="#c4c4c4")
        self.Entry1_7.configure(selectforeground="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.082, rely=0.748, height=24, width=51)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command= lambda: self.control.showdata(self.objarray))
   
        
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Execute''')

        self.Button1_5 = tk.Button(top)
        self.Button1_5.place(relx=0.8, rely=0.748, height=24, width=51)
        self.Button1_5.configure(activebackground="#ececec")
        self.Button1_5.configure(activeforeground="#000000")
        self.Button1_5.configure(background="#d9d9d9")
        self.Button1_5.configure(disabledforeground="#a3a3a3")
        self.Button1_5.configure(foreground="#000000")
        self.Button1_5.configure(highlightbackground="#d9d9d9")
        self.Button1_5.configure(highlightcolor="black")
        self.Button1_5.configure(pady="0")
        self.Button1_5.configure(text='''Close''')
        self.Button1_5.configure(command= lambda  :self.control.closefrom(root))
        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.024, rely=0.204, relheight=0.551, relwidth=0.245)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.bind('<<ListboxSelect>>',self.control.onselect)
        self.control.addlistview(self.Listbox1)
       
        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.4, rely=0.748, height=24, width=40)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='insert')
        self.Button2.configure(command=lambda : self.control.savedata(self.objarray,self.Listbox1))

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.518, rely=0.748, height=24, width=48)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''update''')
        self.Button3.configure(command= lambda: self.control.updatedata(self.objarray,self.Listbox1))
        self.Button3_2 = tk.Button(top)
        self.Button3_2.place(relx=0.659, rely=0.748, height=24, width=48)
        self.Button3_2.configure(activebackground="#ececec")
        self.Button3_2.configure(activeforeground="#000000")
        self.Button3_2.configure(background="#d9d9d9")
        self.Button3_2.configure(disabledforeground="#a3a3a3")
        self.Button3_2.configure(foreground="#000000")
        self.Button3_2.configure(highlightbackground="#d9d9d9")
        self.Button3_2.configure(highlightcolor="black")
        self.Button3_2.configure(pady="0")
        self.Button3_2.configure(text='''delete''')
        self.Button3_2.configure(command= lambda: self.control.deletedata(self.objarray,self.Entry1.get(),self.Listbox1))
        self.objarray.append(self.Entry1)
        self.objarray.append(self.Entry1_1)
        self.objarray.append(self.Entry1_3)
        self.objarray.append(self.Entry1_4)
        self.objarray.append(self.Entry1_5)
        self.objarray.append(self. Entry1_7)
        self.objarray.append(self.Entry1_6)
   
if __name__ == '__main__':
    vp_start_gui()





